/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingBalancesheetsList } from "../funcs/accountingBalancesheetsList.js";
import { accountingBalancesheetsRetrieve } from "../funcs/accountingBalancesheetsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Balancesheets extends ClientSDK {
    /**
     * List  BalanceSheets
     */
    async list(
        request: operations.ListAccountingBalanceSheetsRequest,
        options?: RequestOptions
    ): Promise<PageIterator<operations.ListAccountingBalanceSheetsResponse>> {
        return unwrapResultIterator(accountingBalancesheetsList(this, request, options));
    }

    /**
     * Retrieve BalanceSheets
     *
     * @remarks
     * Retrieve BalanceSheets from any connected Accounting software
     */
    async retrieve(
        request: operations.RetrieveAccountingBalanceSheetRequest,
        options?: RequestOptions
    ): Promise<components.UnifiedAccountingBalancesheetOutput> {
        return unwrapAsync(accountingBalancesheetsRetrieve(this, request, options));
    }
}
