/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmUsersList } from "../funcs/crmUsersList.js";
import { crmUsersRetrieve } from "../funcs/crmUsersRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class PanoraUsers extends ClientSDK {
  /**
   * List  Users
   */
  async list(
    request: operations.ListCrmUsersRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListCrmUsersResponse, { cursor: string }>
  > {
    return unwrapResultIterator(crmUsersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve Users
   *
   * @remarks
   * Retrieve Users from any connected Crm software
   */
  async retrieve(
    request: operations.RetrieveCrmUserRequest,
    options?: RequestOptions,
  ): Promise<components.UnifiedCrmUserOutput> {
    return unwrapAsync(crmUsersRetrieve(
      this,
      request,
      options,
    ));
  }
}
