/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ragQuery } from "../funcs/ragQuery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rag extends ClientSDK {
  /**
   * Query using RAG Search
   *
   * @remarks
   * Query across your connected data sources using RAG Search
   */
  async query(
    request: operations.QueryRequest,
    options?: RequestOptions,
  ): Promise<Array<components.RagQueryOutput>> {
    return unwrapAsync(ragQuery(
      this,
      request,
      options,
    ));
  }
}
