/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateAccountingExpenseRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
    unifiedAccountingExpenseInput: components.UnifiedAccountingExpenseInput;
};

export type CreateAccountingExpenseResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedAccountingExpenseOutput?: components.UnifiedAccountingExpenseOutput | undefined;
};

/** @internal */
export namespace CreateAccountingExpenseRequest$ {
    export const inboundSchema: z.ZodType<CreateAccountingExpenseRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedAccountingExpenseInput: components.UnifiedAccountingExpenseInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedAccountingExpenseInput: "unifiedAccountingExpenseInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedAccountingExpenseInput: components.UnifiedAccountingExpenseInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateAccountingExpenseRequest> =
        z
            .object({
                xConnectionToken: z.string(),
                remoteData: z.boolean().optional(),
                unifiedAccountingExpenseInput:
                    components.UnifiedAccountingExpenseInput$.outboundSchema,
            })
            .transform((v) => {
                return remap$(v, {
                    xConnectionToken: "x-connection-token",
                    remoteData: "remote_data",
                    unifiedAccountingExpenseInput: "UnifiedAccountingExpenseInput",
                });
            });
}

/** @internal */
export namespace CreateAccountingExpenseResponse$ {
    export const inboundSchema: z.ZodType<CreateAccountingExpenseResponse, z.ZodTypeDef, unknown> =
        z
            .object({
                HttpMeta: components.HTTPMetadata$.inboundSchema,
                UnifiedAccountingExpenseOutput:
                    components.UnifiedAccountingExpenseOutput$.inboundSchema.optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    HttpMeta: "httpMeta",
                    UnifiedAccountingExpenseOutput: "unifiedAccountingExpenseOutput",
                });
            });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedAccountingExpenseOutput?:
            | components.UnifiedAccountingExpenseOutput$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateAccountingExpenseResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedAccountingExpenseOutput:
                components.UnifiedAccountingExpenseOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedAccountingExpenseOutput: "UnifiedAccountingExpenseOutput",
            });
        });
}
