/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateMarketingautomationAutomationRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Marketingautomation software.
     */
    remoteData?: boolean | undefined;
    unifiedMarketingautomationAutomationInput: components.UnifiedMarketingautomationAutomationInput;
};

export type CreateMarketingautomationAutomationResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedMarketingautomationAutomationOutput?:
        | components.UnifiedMarketingautomationAutomationOutput
        | undefined;
};

/** @internal */
export namespace CreateMarketingautomationAutomationRequest$ {
    export const inboundSchema: z.ZodType<
        CreateMarketingautomationAutomationRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedMarketingautomationAutomationInput:
                components.UnifiedMarketingautomationAutomationInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedMarketingautomationAutomationInput:
                    "unifiedMarketingautomationAutomationInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedMarketingautomationAutomationInput: components.UnifiedMarketingautomationAutomationInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateMarketingautomationAutomationRequest
    > = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedMarketingautomationAutomationInput:
                components.UnifiedMarketingautomationAutomationInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedMarketingautomationAutomationInput:
                    "UnifiedMarketingautomationAutomationInput",
            });
        });
}

/** @internal */
export namespace CreateMarketingautomationAutomationResponse$ {
    export const inboundSchema: z.ZodType<
        CreateMarketingautomationAutomationResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedMarketingautomationAutomationOutput:
                components.UnifiedMarketingautomationAutomationOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedMarketingautomationAutomationOutput:
                    "unifiedMarketingautomationAutomationOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedMarketingautomationAutomationOutput?:
            | components.UnifiedMarketingautomationAutomationOutput$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateMarketingautomationAutomationResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedMarketingautomationAutomationOutput:
                components.UnifiedMarketingautomationAutomationOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedMarketingautomationAutomationOutput:
                    "UnifiedMarketingautomationAutomationOutput",
            });
        });
}
