/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetDepartmentRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the department you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
};

export type GetDepartmentResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedAtsDepartmentOutput?: components.UnifiedAtsDepartmentOutput | undefined;
};

/** @internal */
export namespace GetDepartmentRequest$ {
    export const inboundSchema: z.ZodType<GetDepartmentRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            id: z.string(),
            remote_data: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        id: string;
        remote_data?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDepartmentRequest> = z
        .object({
            xConnectionToken: z.string(),
            id: z.string(),
            remoteData: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
            });
        });
}

/** @internal */
export namespace GetDepartmentResponse$ {
    export const inboundSchema: z.ZodType<GetDepartmentResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedAtsDepartmentOutput:
                components.UnifiedAtsDepartmentOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedAtsDepartmentOutput: "unifiedAtsDepartmentOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedAtsDepartmentOutput?: components.UnifiedAtsDepartmentOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDepartmentResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedAtsDepartmentOutput:
                components.UnifiedAtsDepartmentOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedAtsDepartmentOutput: "UnifiedAtsDepartmentOutput",
            });
        });
}
