/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetMarketingAutomationContactRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the contact you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Marketingautomation software.
     */
    remoteData?: boolean | undefined;
};

export type GetMarketingAutomationContactResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedMarketingautomationContactOutput?:
        | components.UnifiedMarketingautomationContactOutput
        | undefined;
};

/** @internal */
export namespace GetMarketingAutomationContactRequest$ {
    export const inboundSchema: z.ZodType<
        GetMarketingAutomationContactRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            "x-connection-token": z.string(),
            id: z.string(),
            remote_data: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        id: string;
        remote_data?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetMarketingAutomationContactRequest
    > = z
        .object({
            xConnectionToken: z.string(),
            id: z.string(),
            remoteData: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
            });
        });
}

/** @internal */
export namespace GetMarketingAutomationContactResponse$ {
    export const inboundSchema: z.ZodType<
        GetMarketingAutomationContactResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedMarketingautomationContactOutput:
                components.UnifiedMarketingautomationContactOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedMarketingautomationContactOutput: "unifiedMarketingautomationContactOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedMarketingautomationContactOutput?:
            | components.UnifiedMarketingautomationContactOutput$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetMarketingAutomationContactResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedMarketingautomationContactOutput:
                components.UnifiedMarketingautomationContactOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedMarketingautomationContactOutput: "UnifiedMarketingautomationContactOutput",
            });
        });
}
