/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ImportBatchResponse = {
    httpMeta: components.HTTPMetadata;
    linkedUserResponses?: Array<components.LinkedUserResponse> | undefined;
};

/** @internal */
export const ImportBatchResponse$inboundSchema: z.ZodType<
    ImportBatchResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
        LinkedUserResponses: z.array(components.LinkedUserResponse$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            HttpMeta: "httpMeta",
            LinkedUserResponses: "linkedUserResponses",
        });
    });

/** @internal */
export type ImportBatchResponse$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
    LinkedUserResponses?: Array<components.LinkedUserResponse$Outbound> | undefined;
};

/** @internal */
export const ImportBatchResponse$outboundSchema: z.ZodType<
    ImportBatchResponse$Outbound,
    z.ZodTypeDef,
    ImportBatchResponse
> = z
    .object({
        httpMeta: components.HTTPMetadata$outboundSchema,
        linkedUserResponses: z.array(components.LinkedUserResponse$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            httpMeta: "HttpMeta",
            linkedUserResponses: "LinkedUserResponses",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ImportBatchResponse$ {
    /** @deprecated use `ImportBatchResponse$inboundSchema` instead. */
    export const inboundSchema = ImportBatchResponse$inboundSchema;
    /** @deprecated use `ImportBatchResponse$outboundSchema` instead. */
    export const outboundSchema = ImportBatchResponse$outboundSchema;
    /** @deprecated use `ImportBatchResponse$Outbound` instead. */
    export type Outbound = ImportBatchResponse$Outbound;
}
