/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ListFilestorageDrivesRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original software.
     */
    remoteData?: boolean | undefined;
    /**
     * Set to get the number of records.
     */
    limit?: number | undefined;
    /**
     * Set to get the number of records after this cursor.
     */
    cursor?: string | undefined;
};

export type ListFilestorageDrivesResponseBody = {
    prevCursor: string | null;
    nextCursor: string | null;
    data: Array<components.UnifiedFilestorageDriveOutput>;
};

export type ListFilestorageDrivesResponse = {
    result: ListFilestorageDrivesResponseBody;
};

/** @internal */
export const ListFilestorageDrivesRequest$inboundSchema: z.ZodType<
    ListFilestorageDrivesRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-connection-token": z.string(),
        remote_data: z.boolean().optional(),
        limit: z.number().default(30),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type ListFilestorageDrivesRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
    limit: number;
    cursor?: string | undefined;
};

/** @internal */
export const ListFilestorageDrivesRequest$outboundSchema: z.ZodType<
    ListFilestorageDrivesRequest$Outbound,
    z.ZodTypeDef,
    ListFilestorageDrivesRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
        limit: z.number().default(30),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFilestorageDrivesRequest$ {
    /** @deprecated use `ListFilestorageDrivesRequest$inboundSchema` instead. */
    export const inboundSchema = ListFilestorageDrivesRequest$inboundSchema;
    /** @deprecated use `ListFilestorageDrivesRequest$outboundSchema` instead. */
    export const outboundSchema = ListFilestorageDrivesRequest$outboundSchema;
    /** @deprecated use `ListFilestorageDrivesRequest$Outbound` instead. */
    export type Outbound = ListFilestorageDrivesRequest$Outbound;
}

/** @internal */
export const ListFilestorageDrivesResponseBody$inboundSchema: z.ZodType<
    ListFilestorageDrivesResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        prev_cursor: z.nullable(z.string()),
        next_cursor: z.nullable(z.string()),
        data: z.array(components.UnifiedFilestorageDriveOutput$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            prev_cursor: "prevCursor",
            next_cursor: "nextCursor",
        });
    });

/** @internal */
export type ListFilestorageDrivesResponseBody$Outbound = {
    prev_cursor: string | null;
    next_cursor: string | null;
    data: Array<components.UnifiedFilestorageDriveOutput$Outbound>;
};

/** @internal */
export const ListFilestorageDrivesResponseBody$outboundSchema: z.ZodType<
    ListFilestorageDrivesResponseBody$Outbound,
    z.ZodTypeDef,
    ListFilestorageDrivesResponseBody
> = z
    .object({
        prevCursor: z.nullable(z.string()),
        nextCursor: z.nullable(z.string()),
        data: z.array(components.UnifiedFilestorageDriveOutput$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            prevCursor: "prev_cursor",
            nextCursor: "next_cursor",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFilestorageDrivesResponseBody$ {
    /** @deprecated use `ListFilestorageDrivesResponseBody$inboundSchema` instead. */
    export const inboundSchema = ListFilestorageDrivesResponseBody$inboundSchema;
    /** @deprecated use `ListFilestorageDrivesResponseBody$outboundSchema` instead. */
    export const outboundSchema = ListFilestorageDrivesResponseBody$outboundSchema;
    /** @deprecated use `ListFilestorageDrivesResponseBody$Outbound` instead. */
    export type Outbound = ListFilestorageDrivesResponseBody$Outbound;
}

/** @internal */
export const ListFilestorageDrivesResponse$inboundSchema: z.ZodType<
    ListFilestorageDrivesResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Result: z.lazy(() => ListFilestorageDrivesResponseBody$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            Result: "result",
        });
    });

/** @internal */
export type ListFilestorageDrivesResponse$Outbound = {
    Result: ListFilestorageDrivesResponseBody$Outbound;
};

/** @internal */
export const ListFilestorageDrivesResponse$outboundSchema: z.ZodType<
    ListFilestorageDrivesResponse$Outbound,
    z.ZodTypeDef,
    ListFilestorageDrivesResponse
> = z
    .object({
        result: z.lazy(() => ListFilestorageDrivesResponseBody$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            result: "Result",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFilestorageDrivesResponse$ {
    /** @deprecated use `ListFilestorageDrivesResponse$inboundSchema` instead. */
    export const inboundSchema = ListFilestorageDrivesResponse$inboundSchema;
    /** @deprecated use `ListFilestorageDrivesResponse$outboundSchema` instead. */
    export const outboundSchema = ListFilestorageDrivesResponse$outboundSchema;
    /** @deprecated use `ListFilestorageDrivesResponse$Outbound` instead. */
    export type Outbound = ListFilestorageDrivesResponse$Outbound;
}
