/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RagControllerQueryEmbeddingsResponseBody = {};

/** @internal */
export const RagControllerQueryEmbeddingsResponseBody$inboundSchema: z.ZodType<
  RagControllerQueryEmbeddingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type RagControllerQueryEmbeddingsResponseBody$Outbound = {};

/** @internal */
export const RagControllerQueryEmbeddingsResponseBody$outboundSchema: z.ZodType<
  RagControllerQueryEmbeddingsResponseBody$Outbound,
  z.ZodTypeDef,
  RagControllerQueryEmbeddingsResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RagControllerQueryEmbeddingsResponseBody$ {
  /** @deprecated use `RagControllerQueryEmbeddingsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    RagControllerQueryEmbeddingsResponseBody$inboundSchema;
  /** @deprecated use `RagControllerQueryEmbeddingsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    RagControllerQueryEmbeddingsResponseBody$outboundSchema;
  /** @deprecated use `RagControllerQueryEmbeddingsResponseBody$Outbound` instead. */
  export type Outbound = RagControllerQueryEmbeddingsResponseBody$Outbound;
}
