/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RemoteIdRequest = {
    remoteId: string;
};

export type RemoteIdResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace RemoteIdRequest$ {
    export const inboundSchema: z.ZodType<RemoteIdRequest, z.ZodTypeDef, unknown> = z.object({
        remoteId: z.string(),
    });

    export type Outbound = {
        remoteId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoteIdRequest> = z.object({
        remoteId: z.string(),
    });
}

/** @internal */
export namespace RemoteIdResponse$ {
    export const inboundSchema: z.ZodType<RemoteIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoteIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
            });
        });
}
