/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RetrieveTicketingTagRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the tag you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ticketing software.
     */
    remoteData?: boolean | undefined;
};

export type RetrieveTicketingTagResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedTicketingTagOutput?: components.UnifiedTicketingTagOutput | undefined;
};

/** @internal */
export namespace RetrieveTicketingTagRequest$ {
    export const inboundSchema: z.ZodType<RetrieveTicketingTagRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            id: z.string(),
            remote_data: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        id: string;
        remote_data?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveTicketingTagRequest> = z
        .object({
            xConnectionToken: z.string(),
            id: z.string(),
            remoteData: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
            });
        });
}

/** @internal */
export namespace RetrieveTicketingTagResponse$ {
    export const inboundSchema: z.ZodType<RetrieveTicketingTagResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedTicketingTagOutput:
                components.UnifiedTicketingTagOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedTicketingTagOutput: "unifiedTicketingTagOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedTicketingTagOutput?: components.UnifiedTicketingTagOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveTicketingTagResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedTicketingTagOutput:
                components.UnifiedTicketingTagOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedTicketingTagOutput: "UnifiedTicketingTagOutput",
            });
        });
}
