/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RetrieveAtsTagRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the tag you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
};

export type RetrieveAtsTagResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedAtsTagOutput?: components.UnifiedAtsTagOutput | undefined;
};

/** @internal */
export namespace RetrieveAtsTagRequest$ {
    export const inboundSchema: z.ZodType<RetrieveAtsTagRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            id: z.string(),
            remote_data: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        id: string;
        remote_data?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveAtsTagRequest> = z
        .object({
            xConnectionToken: z.string(),
            id: z.string(),
            remoteData: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
            });
        });
}

/** @internal */
export namespace RetrieveAtsTagResponse$ {
    export const inboundSchema: z.ZodType<RetrieveAtsTagResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedAtsTagOutput: components.UnifiedAtsTagOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedAtsTagOutput: "unifiedAtsTagOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedAtsTagOutput?: components.UnifiedAtsTagOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveAtsTagResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedAtsTagOutput: components.UnifiedAtsTagOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedAtsTagOutput: "UnifiedAtsTagOutput",
            });
        });
}
