/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RetrieveAtsInterviewRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the interview you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
};

export type RetrieveAtsInterviewResponse = {
    httpMeta: components.HTTPMetadata;
    unifiedAtsInterviewOutput?: components.UnifiedAtsInterviewOutput | undefined;
};

/** @internal */
export namespace RetrieveAtsInterviewRequest$ {
    export const inboundSchema: z.ZodType<RetrieveAtsInterviewRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            id: z.string(),
            remote_data: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        id: string;
        remote_data?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveAtsInterviewRequest> = z
        .object({
            xConnectionToken: z.string(),
            id: z.string(),
            remoteData: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
            });
        });
}

/** @internal */
export namespace RetrieveAtsInterviewResponse$ {
    export const inboundSchema: z.ZodType<RetrieveAtsInterviewResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            UnifiedAtsInterviewOutput:
                components.UnifiedAtsInterviewOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedAtsInterviewOutput: "unifiedAtsInterviewOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        UnifiedAtsInterviewOutput?: components.UnifiedAtsInterviewOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RetrieveAtsInterviewResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            unifiedAtsInterviewOutput:
                components.UnifiedAtsInterviewOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedAtsInterviewOutput: "UnifiedAtsInterviewOutput",
            });
        });
}
