/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type RetrieveHrisTimeoffRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * id of the timeoff you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Hris software.
     */
    remoteData?: boolean | undefined;
};

/** @internal */
export const RetrieveHrisTimeoffRequest$inboundSchema: z.ZodType<
    RetrieveHrisTimeoffRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-connection-token": z.string(),
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type RetrieveHrisTimeoffRequest$Outbound = {
    "x-connection-token": string;
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const RetrieveHrisTimeoffRequest$outboundSchema: z.ZodType<
    RetrieveHrisTimeoffRequest$Outbound,
    z.ZodTypeDef,
    RetrieveHrisTimeoffRequest
> = z
    .object({
        xConnectionToken: z.string(),
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetrieveHrisTimeoffRequest$ {
    /** @deprecated use `RetrieveHrisTimeoffRequest$inboundSchema` instead. */
    export const inboundSchema = RetrieveHrisTimeoffRequest$inboundSchema;
    /** @deprecated use `RetrieveHrisTimeoffRequest$outboundSchema` instead. */
    export const outboundSchema = RetrieveHrisTimeoffRequest$outboundSchema;
    /** @deprecated use `RetrieveHrisTimeoffRequest$Outbound` instead. */
    export type Outbound = RetrieveHrisTimeoffRequest$Outbound;
}
