/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePullFrequencyResponseBody = {};

/** @internal */
export const UpdatePullFrequencyResponseBody$inboundSchema: z.ZodType<
  UpdatePullFrequencyResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type UpdatePullFrequencyResponseBody$Outbound = {};

/** @internal */
export const UpdatePullFrequencyResponseBody$outboundSchema: z.ZodType<
  UpdatePullFrequencyResponseBody$Outbound,
  z.ZodTypeDef,
  UpdatePullFrequencyResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePullFrequencyResponseBody$ {
  /** @deprecated use `UpdatePullFrequencyResponseBody$inboundSchema` instead. */
  export const inboundSchema = UpdatePullFrequencyResponseBody$inboundSchema;
  /** @deprecated use `UpdatePullFrequencyResponseBody$outboundSchema` instead. */
  export const outboundSchema = UpdatePullFrequencyResponseBody$outboundSchema;
  /** @deprecated use `UpdatePullFrequencyResponseBody$Outbound` instead. */
  export type Outbound = UpdatePullFrequencyResponseBody$Outbound;
}

export function updatePullFrequencyResponseBodyToJSON(
  updatePullFrequencyResponseBody: UpdatePullFrequencyResponseBody,
): string {
  return JSON.stringify(
    UpdatePullFrequencyResponseBody$outboundSchema.parse(
      updatePullFrequencyResponseBody,
    ),
  );
}

export function updatePullFrequencyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePullFrequencyResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePullFrequencyResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePullFrequencyResponseBody' from JSON`,
  );
}
