/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnifiedCrmEngagementInputFieldMappings = {};

export type UnifiedCrmEngagementInput = {
    /**
     * The content of the engagement
     */
    content?: string | undefined;
    /**
     * The direction of the engagement. Authorized values are INBOUND or OUTBOUND
     */
    direction?: string | undefined;
    /**
     * The subject of the engagement
     */
    subject?: string | undefined;
    /**
     * The start time of the engagement
     */
    startAt?: Date | undefined;
    /**
     * The end time of the engagement
     */
    endTime?: Date | undefined;
    /**
     * The type of the engagement. Authorized values are EMAIL, CALL or MEETING
     */
    type: string;
    /**
     * The UUID of the user tied to the engagement
     */
    userId?: string | undefined;
    /**
     * The UUID of the company tied to the engagement
     */
    companyId?: string | undefined;
    /**
     * The UUIDs of contacts tied to the engagement object
     */
    contacts?: Array<string> | undefined;
    fieldMappings: UnifiedCrmEngagementInputFieldMappings;
};

/** @internal */
export const UnifiedCrmEngagementInputFieldMappings$inboundSchema: z.ZodType<
    UnifiedCrmEngagementInputFieldMappings,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedCrmEngagementInputFieldMappings$Outbound = {};

/** @internal */
export const UnifiedCrmEngagementInputFieldMappings$outboundSchema: z.ZodType<
    UnifiedCrmEngagementInputFieldMappings$Outbound,
    z.ZodTypeDef,
    UnifiedCrmEngagementInputFieldMappings
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedCrmEngagementInputFieldMappings$ {
    /** @deprecated use `UnifiedCrmEngagementInputFieldMappings$inboundSchema` instead. */
    export const inboundSchema = UnifiedCrmEngagementInputFieldMappings$inboundSchema;
    /** @deprecated use `UnifiedCrmEngagementInputFieldMappings$outboundSchema` instead. */
    export const outboundSchema = UnifiedCrmEngagementInputFieldMappings$outboundSchema;
    /** @deprecated use `UnifiedCrmEngagementInputFieldMappings$Outbound` instead. */
    export type Outbound = UnifiedCrmEngagementInputFieldMappings$Outbound;
}

/** @internal */
export const UnifiedCrmEngagementInput$inboundSchema: z.ZodType<
    UnifiedCrmEngagementInput,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        content: z.string().optional(),
        direction: z.string().optional(),
        subject: z.string().optional(),
        start_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        end_time: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        type: z.string(),
        user_id: z.string().optional(),
        company_id: z.string().optional(),
        contacts: z.array(z.string()).optional(),
        field_mappings: z.lazy(() => UnifiedCrmEngagementInputFieldMappings$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            start_at: "startAt",
            end_time: "endTime",
            user_id: "userId",
            company_id: "companyId",
            field_mappings: "fieldMappings",
        });
    });

/** @internal */
export type UnifiedCrmEngagementInput$Outbound = {
    content?: string | undefined;
    direction?: string | undefined;
    subject?: string | undefined;
    start_at?: string | undefined;
    end_time?: string | undefined;
    type: string;
    user_id?: string | undefined;
    company_id?: string | undefined;
    contacts?: Array<string> | undefined;
    field_mappings: UnifiedCrmEngagementInputFieldMappings$Outbound;
};

/** @internal */
export const UnifiedCrmEngagementInput$outboundSchema: z.ZodType<
    UnifiedCrmEngagementInput$Outbound,
    z.ZodTypeDef,
    UnifiedCrmEngagementInput
> = z
    .object({
        content: z.string().optional(),
        direction: z.string().optional(),
        subject: z.string().optional(),
        startAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        endTime: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        type: z.string(),
        userId: z.string().optional(),
        companyId: z.string().optional(),
        contacts: z.array(z.string()).optional(),
        fieldMappings: z.lazy(() => UnifiedCrmEngagementInputFieldMappings$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            startAt: "start_at",
            endTime: "end_time",
            userId: "user_id",
            companyId: "company_id",
            fieldMappings: "field_mappings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedCrmEngagementInput$ {
    /** @deprecated use `UnifiedCrmEngagementInput$inboundSchema` instead. */
    export const inboundSchema = UnifiedCrmEngagementInput$inboundSchema;
    /** @deprecated use `UnifiedCrmEngagementInput$outboundSchema` instead. */
    export const outboundSchema = UnifiedCrmEngagementInput$outboundSchema;
    /** @deprecated use `UnifiedCrmEngagementInput$Outbound` instead. */
    export type Outbound = UnifiedCrmEngagementInput$Outbound;
}
