/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    LineItem,
    LineItem$inboundSchema,
    LineItem$Outbound,
    LineItem$outboundSchema,
} from "./lineitem.js";
import * as z from "zod";

/**
 * The currency used in the balance sheet
 */
export enum UnifiedAccountingBalancesheetOutputCurrency {
    Aed = "AED",
    Afn = "AFN",
    All = "ALL",
    Amd = "AMD",
    Ang = "ANG",
    Aoa = "AOA",
    Ars = "ARS",
    Aud = "AUD",
    Awg = "AWG",
    Azn = "AZN",
    Bam = "BAM",
    Bbd = "BBD",
    Bdt = "BDT",
    Bgn = "BGN",
    Bhd = "BHD",
    Bif = "BIF",
    Bmd = "BMD",
    Bnd = "BND",
    Bob = "BOB",
    Brl = "BRL",
    Bsd = "BSD",
    Btn = "BTN",
    Bwp = "BWP",
    Byn = "BYN",
    Bzd = "BZD",
    Cad = "CAD",
    Cdf = "CDF",
    Chf = "CHF",
    Clp = "CLP",
    Cny = "CNY",
    Cop = "COP",
    Crc = "CRC",
    Cup = "CUP",
    Cve = "CVE",
    Czk = "CZK",
    Djf = "DJF",
    Dkk = "DKK",
    Dop = "DOP",
    Dzd = "DZD",
    Egp = "EGP",
    Ern = "ERN",
    Etb = "ETB",
    Eur = "EUR",
    Fjd = "FJD",
    Fkp = "FKP",
    Fok = "FOK",
    Gbp = "GBP",
    Gel = "GEL",
    Ggp = "GGP",
    Ghs = "GHS",
    Gip = "GIP",
    Gmd = "GMD",
    Gnf = "GNF",
    Gtq = "GTQ",
    Gyd = "GYD",
    Hkd = "HKD",
    Hnl = "HNL",
    Hrk = "HRK",
    Htg = "HTG",
    Huf = "HUF",
    Idr = "IDR",
    Ils = "ILS",
    Imp = "IMP",
    Inr = "INR",
    Iqd = "IQD",
    Irr = "IRR",
    Isk = "ISK",
    Jep = "JEP",
    Jmd = "JMD",
    Jod = "JOD",
    Jpy = "JPY",
    Kes = "KES",
    Kgs = "KGS",
    Khr = "KHR",
    Kid = "KID",
    Kmf = "KMF",
    Krw = "KRW",
    Kwd = "KWD",
    Kyd = "KYD",
    Kzt = "KZT",
    Lak = "LAK",
    Lbp = "LBP",
    Lkr = "LKR",
    Lrd = "LRD",
    Lsl = "LSL",
    Lyd = "LYD",
    Mad = "MAD",
    Mdl = "MDL",
    Mga = "MGA",
    Mkd = "MKD",
    Mmk = "MMK",
    Mnt = "MNT",
    Mop = "MOP",
    Mru = "MRU",
    Mur = "MUR",
    Mvr = "MVR",
    Mwk = "MWK",
    Mxn = "MXN",
    Myr = "MYR",
    Mzn = "MZN",
    Nad = "NAD",
    Ngn = "NGN",
    Nio = "NIO",
    Nok = "NOK",
    Npr = "NPR",
    Nzd = "NZD",
    Omr = "OMR",
    Pab = "PAB",
    Pen = "PEN",
    Pgk = "PGK",
    Php = "PHP",
    Pkr = "PKR",
    Pln = "PLN",
    Pyg = "PYG",
    Qar = "QAR",
    Ron = "RON",
    Rsd = "RSD",
    Rub = "RUB",
    Rwf = "RWF",
    Sar = "SAR",
    Sbd = "SBD",
    Scr = "SCR",
    Sdg = "SDG",
    Sek = "SEK",
    Sgd = "SGD",
    Shp = "SHP",
    Sle = "SLE",
    Sll = "SLL",
    Sos = "SOS",
    Srd = "SRD",
    Ssp = "SSP",
    Stn = "STN",
    Syp = "SYP",
    Szl = "SZL",
    Thb = "THB",
    Tjs = "TJS",
    Tmt = "TMT",
    Tnd = "TND",
    Top = "TOP",
    Try = "TRY",
    Ttd = "TTD",
    Tvd = "TVD",
    Twd = "TWD",
    Tzs = "TZS",
    Uah = "UAH",
    Ugx = "UGX",
    Usd = "USD",
    Uyu = "UYU",
    Uzs = "UZS",
    Ves = "VES",
    Vnd = "VND",
    Vuv = "VUV",
    Wst = "WST",
    Xaf = "XAF",
    Xcd = "XCD",
    Xdr = "XDR",
    Xof = "XOF",
    Xpf = "XPF",
    Yer = "YER",
    Zar = "ZAR",
    Zmw = "ZMW",
    Zwl = "ZWL",
}

/**
 * The custom field mappings of the object between the remote 3rd party & Panora
 */
export type UnifiedAccountingBalancesheetOutputFieldMappings = {};

/**
 * The remote data of the balance sheet in the context of the 3rd Party
 */
export type UnifiedAccountingBalancesheetOutputRemoteData = {};

export type UnifiedAccountingBalancesheetOutput = {
    /**
     * The name of the balance sheet
     */
    name?: string | null | undefined;
    /**
     * The currency used in the balance sheet
     */
    currency?: UnifiedAccountingBalancesheetOutputCurrency | null | undefined;
    /**
     * The UUID of the associated company info
     */
    companyInfoId?: string | null | undefined;
    /**
     * The date of the balance sheet
     */
    date?: Date | null | undefined;
    /**
     * The net assets value
     */
    netAssets?: number | null | undefined;
    /**
     * The list of assets
     */
    assets?: Array<string> | null | undefined;
    /**
     * The list of liabilities
     */
    liabilities?: Array<string> | null | undefined;
    /**
     * The list of equity items
     */
    equity?: Array<string> | null | undefined;
    /**
     * The date when the balance sheet was generated in the remote system
     */
    remoteGeneratedAt?: Date | null | undefined;
    /**
     * The report items associated with this balance sheet
     */
    lineItems?: Array<LineItem> | undefined;
    /**
     * The custom field mappings of the object between the remote 3rd party & Panora
     */
    fieldMappings?: UnifiedAccountingBalancesheetOutputFieldMappings | null | undefined;
    /**
     * The UUID of the balance sheet record
     */
    id?: string | null | undefined;
    /**
     * The remote ID of the balance sheet in the context of the 3rd Party
     */
    remoteId?: string | null | undefined;
    /**
     * The remote data of the balance sheet in the context of the 3rd Party
     */
    remoteData?: UnifiedAccountingBalancesheetOutputRemoteData | null | undefined;
    /**
     * The created date of the balance sheet record
     */
    createdAt?: Date | null | undefined;
    /**
     * The last modified date of the balance sheet record
     */
    modifiedAt?: Date | null | undefined;
};

/** @internal */
export const UnifiedAccountingBalancesheetOutputCurrency$inboundSchema: z.ZodNativeEnum<
    typeof UnifiedAccountingBalancesheetOutputCurrency
> = z.nativeEnum(UnifiedAccountingBalancesheetOutputCurrency);

/** @internal */
export const UnifiedAccountingBalancesheetOutputCurrency$outboundSchema: z.ZodNativeEnum<
    typeof UnifiedAccountingBalancesheetOutputCurrency
> = UnifiedAccountingBalancesheetOutputCurrency$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedAccountingBalancesheetOutputCurrency$ {
    /** @deprecated use `UnifiedAccountingBalancesheetOutputCurrency$inboundSchema` instead. */
    export const inboundSchema = UnifiedAccountingBalancesheetOutputCurrency$inboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutputCurrency$outboundSchema` instead. */
    export const outboundSchema = UnifiedAccountingBalancesheetOutputCurrency$outboundSchema;
}

/** @internal */
export const UnifiedAccountingBalancesheetOutputFieldMappings$inboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutputFieldMappings,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedAccountingBalancesheetOutputFieldMappings$Outbound = {};

/** @internal */
export const UnifiedAccountingBalancesheetOutputFieldMappings$outboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutputFieldMappings$Outbound,
    z.ZodTypeDef,
    UnifiedAccountingBalancesheetOutputFieldMappings
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedAccountingBalancesheetOutputFieldMappings$ {
    /** @deprecated use `UnifiedAccountingBalancesheetOutputFieldMappings$inboundSchema` instead. */
    export const inboundSchema = UnifiedAccountingBalancesheetOutputFieldMappings$inboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutputFieldMappings$outboundSchema` instead. */
    export const outboundSchema = UnifiedAccountingBalancesheetOutputFieldMappings$outboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutputFieldMappings$Outbound` instead. */
    export type Outbound = UnifiedAccountingBalancesheetOutputFieldMappings$Outbound;
}

/** @internal */
export const UnifiedAccountingBalancesheetOutputRemoteData$inboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutputRemoteData,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedAccountingBalancesheetOutputRemoteData$Outbound = {};

/** @internal */
export const UnifiedAccountingBalancesheetOutputRemoteData$outboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutputRemoteData$Outbound,
    z.ZodTypeDef,
    UnifiedAccountingBalancesheetOutputRemoteData
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedAccountingBalancesheetOutputRemoteData$ {
    /** @deprecated use `UnifiedAccountingBalancesheetOutputRemoteData$inboundSchema` instead. */
    export const inboundSchema = UnifiedAccountingBalancesheetOutputRemoteData$inboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutputRemoteData$outboundSchema` instead. */
    export const outboundSchema = UnifiedAccountingBalancesheetOutputRemoteData$outboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutputRemoteData$Outbound` instead. */
    export type Outbound = UnifiedAccountingBalancesheetOutputRemoteData$Outbound;
}

/** @internal */
export const UnifiedAccountingBalancesheetOutput$inboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutput,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        name: z.nullable(z.string()).optional(),
        currency: z.nullable(UnifiedAccountingBalancesheetOutputCurrency$inboundSchema).optional(),
        company_info_id: z.nullable(z.string()).optional(),
        date: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
        net_assets: z.nullable(z.number()).optional(),
        assets: z.nullable(z.array(z.string())).optional(),
        liabilities: z.nullable(z.array(z.string())).optional(),
        equity: z.nullable(z.array(z.string())).optional(),
        remote_generated_at: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
        line_items: z.array(LineItem$inboundSchema).optional(),
        field_mappings: z
            .nullable(z.lazy(() => UnifiedAccountingBalancesheetOutputFieldMappings$inboundSchema))
            .optional(),
        id: z.nullable(z.string()).optional(),
        remote_id: z.nullable(z.string()).optional(),
        remote_data: z
            .nullable(z.lazy(() => UnifiedAccountingBalancesheetOutputRemoteData$inboundSchema))
            .optional(),
        created_at: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
        modified_at: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            company_info_id: "companyInfoId",
            net_assets: "netAssets",
            remote_generated_at: "remoteGeneratedAt",
            line_items: "lineItems",
            field_mappings: "fieldMappings",
            remote_id: "remoteId",
            remote_data: "remoteData",
            created_at: "createdAt",
            modified_at: "modifiedAt",
        });
    });

/** @internal */
export type UnifiedAccountingBalancesheetOutput$Outbound = {
    name?: string | null | undefined;
    currency?: string | null | undefined;
    company_info_id?: string | null | undefined;
    date?: string | null | undefined;
    net_assets?: number | null | undefined;
    assets?: Array<string> | null | undefined;
    liabilities?: Array<string> | null | undefined;
    equity?: Array<string> | null | undefined;
    remote_generated_at?: string | null | undefined;
    line_items?: Array<LineItem$Outbound> | undefined;
    field_mappings?: UnifiedAccountingBalancesheetOutputFieldMappings$Outbound | null | undefined;
    id?: string | null | undefined;
    remote_id?: string | null | undefined;
    remote_data?: UnifiedAccountingBalancesheetOutputRemoteData$Outbound | null | undefined;
    created_at?: string | null | undefined;
    modified_at?: string | null | undefined;
};

/** @internal */
export const UnifiedAccountingBalancesheetOutput$outboundSchema: z.ZodType<
    UnifiedAccountingBalancesheetOutput$Outbound,
    z.ZodTypeDef,
    UnifiedAccountingBalancesheetOutput
> = z
    .object({
        name: z.nullable(z.string()).optional(),
        currency: z.nullable(UnifiedAccountingBalancesheetOutputCurrency$outboundSchema).optional(),
        companyInfoId: z.nullable(z.string()).optional(),
        date: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        netAssets: z.nullable(z.number()).optional(),
        assets: z.nullable(z.array(z.string())).optional(),
        liabilities: z.nullable(z.array(z.string())).optional(),
        equity: z.nullable(z.array(z.string())).optional(),
        remoteGeneratedAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        lineItems: z.array(LineItem$outboundSchema).optional(),
        fieldMappings: z
            .nullable(z.lazy(() => UnifiedAccountingBalancesheetOutputFieldMappings$outboundSchema))
            .optional(),
        id: z.nullable(z.string()).optional(),
        remoteId: z.nullable(z.string()).optional(),
        remoteData: z
            .nullable(z.lazy(() => UnifiedAccountingBalancesheetOutputRemoteData$outboundSchema))
            .optional(),
        createdAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        modifiedAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            companyInfoId: "company_info_id",
            netAssets: "net_assets",
            remoteGeneratedAt: "remote_generated_at",
            lineItems: "line_items",
            fieldMappings: "field_mappings",
            remoteId: "remote_id",
            remoteData: "remote_data",
            createdAt: "created_at",
            modifiedAt: "modified_at",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedAccountingBalancesheetOutput$ {
    /** @deprecated use `UnifiedAccountingBalancesheetOutput$inboundSchema` instead. */
    export const inboundSchema = UnifiedAccountingBalancesheetOutput$inboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutput$outboundSchema` instead. */
    export const outboundSchema = UnifiedAccountingBalancesheetOutput$outboundSchema;
    /** @deprecated use `UnifiedAccountingBalancesheetOutput$Outbound` instead. */
    export type Outbound = UnifiedAccountingBalancesheetOutput$Outbound;
}
