/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type UnifiedCrmNoteOutput = {
  /**
   * The content of the note
   */
  content: string | null;
  /**
   * The UUID of the user tied to the note
   */
  userId?: string | null | undefined;
  /**
   * The UUID of the company tied to the note
   */
  companyId?: string | null | undefined;
  /**
   * The UUID of the contact tied to the note
   */
  contactId?: string | null | undefined;
  /**
   * The UUID of the deal tied to the note
   */
  dealId?: string | null | undefined;
  /**
   * The custom field mappings of the note between the remote 3rd party & Panora
   */
  fieldMappings?: { [k: string]: any } | null | undefined;
  /**
   * The UUID of the note
   */
  id?: string | null | undefined;
  /**
   * The ID of the note in the context of the Crm 3rd Party
   */
  remoteId?: string | null | undefined;
  /**
   * The remote data of the note in the context of the Crm 3rd Party
   */
  remoteData?: { [k: string]: any } | null | undefined;
  /**
   * The created date of the object
   */
  createdAt?: Date | null | undefined;
  /**
   * The modified date of the object
   */
  modifiedAt?: Date | null | undefined;
};

/** @internal */
export const UnifiedCrmNoteOutput$inboundSchema: z.ZodType<
  UnifiedCrmNoteOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.nullable(z.string()),
  user_id: z.nullable(z.string()).optional(),
  company_id: z.nullable(z.string()).optional(),
  contact_id: z.nullable(z.string()).optional(),
  deal_id: z.nullable(z.string()).optional(),
  field_mappings: z.nullable(z.record(z.any())).optional(),
  id: z.nullable(z.string()).optional(),
  remote_id: z.nullable(z.string()).optional(),
  remote_data: z.nullable(z.record(z.any())).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  modified_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "company_id": "companyId",
    "contact_id": "contactId",
    "deal_id": "dealId",
    "field_mappings": "fieldMappings",
    "remote_id": "remoteId",
    "remote_data": "remoteData",
    "created_at": "createdAt",
    "modified_at": "modifiedAt",
  });
});

/** @internal */
export type UnifiedCrmNoteOutput$Outbound = {
  content: string | null;
  user_id?: string | null | undefined;
  company_id?: string | null | undefined;
  contact_id?: string | null | undefined;
  deal_id?: string | null | undefined;
  field_mappings?: { [k: string]: any } | null | undefined;
  id?: string | null | undefined;
  remote_id?: string | null | undefined;
  remote_data?: { [k: string]: any } | null | undefined;
  created_at?: string | null | undefined;
  modified_at?: string | null | undefined;
};

/** @internal */
export const UnifiedCrmNoteOutput$outboundSchema: z.ZodType<
  UnifiedCrmNoteOutput$Outbound,
  z.ZodTypeDef,
  UnifiedCrmNoteOutput
> = z.object({
  content: z.nullable(z.string()),
  userId: z.nullable(z.string()).optional(),
  companyId: z.nullable(z.string()).optional(),
  contactId: z.nullable(z.string()).optional(),
  dealId: z.nullable(z.string()).optional(),
  fieldMappings: z.nullable(z.record(z.any())).optional(),
  id: z.nullable(z.string()).optional(),
  remoteId: z.nullable(z.string()).optional(),
  remoteData: z.nullable(z.record(z.any())).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
    companyId: "company_id",
    contactId: "contact_id",
    dealId: "deal_id",
    fieldMappings: "field_mappings",
    remoteId: "remote_id",
    remoteData: "remote_data",
    createdAt: "created_at",
    modifiedAt: "modified_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedCrmNoteOutput$ {
  /** @deprecated use `UnifiedCrmNoteOutput$inboundSchema` instead. */
  export const inboundSchema = UnifiedCrmNoteOutput$inboundSchema;
  /** @deprecated use `UnifiedCrmNoteOutput$outboundSchema` instead. */
  export const outboundSchema = UnifiedCrmNoteOutput$outboundSchema;
  /** @deprecated use `UnifiedCrmNoteOutput$Outbound` instead. */
  export type Outbound = UnifiedCrmNoteOutput$Outbound;
}
