/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedAccountingPaymentInput = {};

/** @internal */
export const UnifiedAccountingPaymentInput$inboundSchema: z.ZodType<
    UnifiedAccountingPaymentInput,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedAccountingPaymentInput$Outbound = {};

/** @internal */
export const UnifiedAccountingPaymentInput$outboundSchema: z.ZodType<
    UnifiedAccountingPaymentInput$Outbound,
    z.ZodTypeDef,
    UnifiedAccountingPaymentInput
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedAccountingPaymentInput$ {
    /** @deprecated use `UnifiedAccountingPaymentInput$inboundSchema` instead. */
    export const inboundSchema = UnifiedAccountingPaymentInput$inboundSchema;
    /** @deprecated use `UnifiedAccountingPaymentInput$outboundSchema` instead. */
    export const outboundSchema = UnifiedAccountingPaymentInput$outboundSchema;
    /** @deprecated use `UnifiedAccountingPaymentInput$Outbound` instead. */
    export type Outbound = UnifiedAccountingPaymentInput$Outbound;
}
