/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedHrisLocationOutput = {};

/** @internal */
export namespace UnifiedHrisLocationOutput$ {
    export const inboundSchema: z.ZodType<UnifiedHrisLocationOutput, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedHrisLocationOutput> =
        z.object({});
}
