/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type UnifiedFilestorageUserOutput = {
  /**
   * The name of the user
   */
  name: string | null;
  /**
   * The email of the user
   */
  email: string | null;
  /**
   * Whether the user is the one who linked this account.
   */
  isMe: boolean | null;
  /**
   * The custom field mappings of the object between the remote 3rd party & Panora
   */
  fieldMappings?: { [k: string]: any } | null | undefined;
  /**
   * The UUID of the user
   */
  id?: string | null | undefined;
  /**
   * The id of the user in the context of the 3rd Party
   */
  remoteId?: string | null | undefined;
  /**
   * The remote data of the user in the context of the 3rd Party
   */
  remoteData?: { [k: string]: any } | null | undefined;
  /**
   * The created date of the object
   */
  createdAt?: Date | null | undefined;
  /**
   * The modified date of the object
   */
  modifiedAt?: Date | null | undefined;
};

/** @internal */
export const UnifiedFilestorageUserOutput$inboundSchema: z.ZodType<
  UnifiedFilestorageUserOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()),
  email: z.nullable(z.string()),
  is_me: z.nullable(z.boolean()),
  field_mappings: z.nullable(z.record(z.any())).optional(),
  id: z.nullable(z.string()).optional(),
  remote_id: z.nullable(z.string()).optional(),
  remote_data: z.nullable(z.record(z.any())).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  modified_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "is_me": "isMe",
    "field_mappings": "fieldMappings",
    "remote_id": "remoteId",
    "remote_data": "remoteData",
    "created_at": "createdAt",
    "modified_at": "modifiedAt",
  });
});

/** @internal */
export type UnifiedFilestorageUserOutput$Outbound = {
  name: string | null;
  email: string | null;
  is_me: boolean | null;
  field_mappings?: { [k: string]: any } | null | undefined;
  id?: string | null | undefined;
  remote_id?: string | null | undefined;
  remote_data?: { [k: string]: any } | null | undefined;
  created_at?: string | null | undefined;
  modified_at?: string | null | undefined;
};

/** @internal */
export const UnifiedFilestorageUserOutput$outboundSchema: z.ZodType<
  UnifiedFilestorageUserOutput$Outbound,
  z.ZodTypeDef,
  UnifiedFilestorageUserOutput
> = z.object({
  name: z.nullable(z.string()),
  email: z.nullable(z.string()),
  isMe: z.nullable(z.boolean()),
  fieldMappings: z.nullable(z.record(z.any())).optional(),
  id: z.nullable(z.string()).optional(),
  remoteId: z.nullable(z.string()).optional(),
  remoteData: z.nullable(z.record(z.any())).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    isMe: "is_me",
    fieldMappings: "field_mappings",
    remoteId: "remote_id",
    remoteData: "remote_data",
    createdAt: "created_at",
    modifiedAt: "modified_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedFilestorageUserOutput$ {
  /** @deprecated use `UnifiedFilestorageUserOutput$inboundSchema` instead. */
  export const inboundSchema = UnifiedFilestorageUserOutput$inboundSchema;
  /** @deprecated use `UnifiedFilestorageUserOutput$outboundSchema` instead. */
  export const outboundSchema = UnifiedFilestorageUserOutput$outboundSchema;
  /** @deprecated use `UnifiedFilestorageUserOutput$Outbound` instead. */
  export type Outbound = UnifiedFilestorageUserOutput$Outbound;
}
