/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedAccountingPhonenumberOutput = {};

/** @internal */
export namespace UnifiedAccountingPhonenumberOutput$ {
    export const inboundSchema: z.ZodType<
        UnifiedAccountingPhonenumberOutput,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UnifiedAccountingPhonenumberOutput
    > = z.object({});
}
