/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedHrisDependentOutput = {};

/** @internal */
export namespace UnifiedHrisDependentOutput$ {
    export const inboundSchema: z.ZodType<UnifiedHrisDependentOutput, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedHrisDependentOutput> =
        z.object({});
}
